CREATE TABLE pipeline_dataset(
  id integer primary key AUTOINCREMENT
  ,Time NUMERIC(7,2) NOT NULL
  ,Q    NUMERIC(11,9) NOT NULL
  ,P1   NUMERIC(12,9) NOT NULL
  ,P2   NUMERIC(12,9) NOT NULL
  ,P3   NUMERIC(12,9) NOT NULL
  ,P4   NUMERIC(12,9) NOT NULL
  ,P5   NUMERIC(11,9) NOT NULL
);
